public: true
type: "docs"
category: "collection management and development"
tags:
  - "policy"
  - "reappraisal"
title: "Reappraisal Policy"
description: "Principles and criteria for archival reappraisal."
pages:
  - ["Reappraisal Policy", "index"]
