public: true
type: "docs"
category: "collection development and management"
tags:
  - "policy"
title: "Reappraisal Policy"
description: "Principles and criteria for archival reappraisal."
pages:
  - ["Reappraisal Policy", "index"]
